baseurl = "https://bluepaws.jp/"
title = "BLUE PAWS(ãƒ–ãƒ«ãƒ¼ãƒ‘ã‚¦ã‚º) - è—¤æ²¢å¸‚ã®ãƒˆãƒªãƒŸãƒ³ã‚°ã‚µãƒ­ãƒ³/ãƒ‰ãƒƒã‚°ã‚µãƒ­ãƒ³"
theme = "hugo-universal-theme-master"
themesDir = "/themes"
languageCode = "ja"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "ja"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

# path for css
canonifyurls = true

[menu]

# Main menu

[[menu.main]]
#    name = "Home"
#    url  = "/"
#    weight = 1

[[menu.main]]
#    name = "ãƒ–ãƒ­"
#    url  = "/blogs/"
#    weight = 2

[[menu.main]]
#    name = "FAQ"
#    identifier = "faq"
#    url  = "/faq/"
#    weight = 3

[[menu.main]]
#    name = "Contact"
#    url  = "/contact/"
#    weight = 4

# Top bar social links menu

[[menu.topbar]]
#    weight = 1
#    name = "GitHub"
#    url = "https://github.com/devcows/hugo-universal-theme"
#    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
#    weight = 2
#    name = "Facebook"
#    url = "http://facebook.com"
#    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
#    weight = 3
#    name = "Twitter"
#    url = "http://twitter.com"
#    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
#      weight = 1
#      name = "line"
#      url = "https://line.me/R/ti/p/%40zwb3497w"
      pre = """<img height="36" border="0" alt="å‹ã ã¡è¿½åŠ " src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png">"""

[[menu.topbar]]
#    weight = 4
#    name = "Email"
#    url = "mailto:your@email.com"
#    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["ãƒˆãƒªãƒŸãƒ³ã‚°ã‚µãƒ­ãƒ³", "ãƒšãƒƒãƒˆã‚µãƒ­ãƒ³", "ãƒ‰ãƒƒã‚°ã‚µãƒ­ãƒ³"]
    defaultDescription = "ãƒ¯ãƒ³ã¡ã‚ƒã‚“ã‚’å¯æ„›ããƒˆãƒªãƒŸãƒ³ã‚°ã€‚ã‚²ãƒ¼ã‚¸ãƒ•ãƒªãƒ¼ã§ã€ãƒ¯ãƒ³ã‚³ã«å¿«é©ãªç’°å¢ƒã§ã™ã€‚ãƒ—ãƒ©ã‚¤ãƒ™ãƒ¼ãƒˆã‚µãƒ­ãƒ³ãªã®ã§ã€ä»–ã®ãƒ¯ãƒ³ã‚³ãŒè‹¦æ‰‹ã§ã‚‚å®‰å¿ƒã€‚è—¤æ²¢å¸‚ã®æ±Ÿãƒå³¶é§…è¿‘ãã®ãƒ‰ãƒƒã‚°ã‚µãƒ­ãƒ³/ãƒˆãƒªãƒŸãƒ³ã‚°ã‚µãƒ­ãƒ³ BLUE PAWS(ãƒ–ãƒ«ãƒ¼ãƒ‘ã‚¦ã‚º)ã§ã™ã€‚"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyBmrmhVxBRy-JOHuiFoxA-LHanXSMy3KJM"

    #Â Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    #Â Enable the contact form by entering your Formspree.io email
    email = "bluepaws2018@gmail.com"

    about_us = ""
    copyright = "Copyright (c) 2018, BLUE PAWS all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "/img/logo-small.svg"
    address = """<p>
        <h3>ã”äºˆç´„ãƒ»ãŠå•åˆã›å…ˆ</h3><p><a href="tel:050-3196-3129" data-animate-hover="pulse" onclick="return gtag_report_conversion('tel:050-3196-3129');"><i class="fa fa-phone"></i>TEL:050-3196-3129</a></p>
        <p><a href="mailto:bluepaws2018@gmail.com" data-animate-hover="pulse" onclick="return gtag_report_conversion('mailto:bluepaws2018@gmail.com');"><i class="fa fa-envelope"></i>bluepaws2018@gmail.com</a></p>
        <p><a href="https://line.me/R/ti/p/%40zwb3497w"><img height="36" border="0" alt="LINEå‹ã ã¡è¿½åŠ " src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" onclick="return gtag_report_conversion('https://line.me/R/ti/p/%40zwb3497w');"></a></p>
        <p>LINEã®å‹ã ã¡ç™»éŒ²ã§ã€åˆå›ç‰¹å…¸ãªã©ãŠå¾—ãªæƒ…å ±ã‚’ãŠå±Šã‘ã—ã¾ã™ã€‚</p>
        <p>å—ä»˜/å–¶æ¥­æ™‚é–“ 9:00ï½18:00ã€å®šä¼‘æ—¥:æœ¨æ›œã€æ—¥æ›œã€ç¥ç¥­æ—¥ <br>( ãŠæ°—è»½ã«ãŠå•åˆã›ä¸‹ã•ã„ã€‚LINEã¯ã€ã„ã¤ã§ã‚‚ãŠå•åˆã›çµæ§‹ã§ã™)</p>
      """
    social = """<h3>ã‚½ãƒ¼ã‚·ãƒ£ãƒ«</h3><a href="https://www.facebook.com/bluepaws2018/"  target="_blank"><img border="0" alt="facebookãƒšãƒ¼ã‚¸ã¸" src="/img/FB-FindUsonFacebook-online-144_ja_JP.png" onclick="return gtag_report_conversion('https://www.facebook.com/bluepaws2018/');" style="background-color: white;"></a><br><a href="https://www.instagram.com/bluepaws2018/"  target="_blank"><img border="0" alt="Instagramã¸" src="/img/instalogo.png" onclick="return gtag_report_conversion('https://www.instagram.com/bluepaws2018/');"></a>"""

    hokanmenkyo = """<h3>ç¬¬ä¸€ç¨®å‹•ç‰©å–æ‰±æ¥­ã®ç™»éŒ²</h3> ç¥å¥ˆå·çœŒç¬¬ä¸€ç¨®å‹•ç‰©å–æ‰±æ¥­ç™»éŒ² å‹•ä¿ç¬¬170303å·<br>æœ‰åŠ¹æœŸé™ï¼š2023å¹´1æœˆ9æ—¥<br>å‹•ç‰©å–æ‰±è²¬ä»»è€…ï¼šå²¡ç”°æœ‰ç´€"""

    latitude = "35.315133"
    longitude = "139.486057"
    direction = "è—¤æ²¢å¸‚ç‰‡ç€¬3-1-29"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">ã”äºˆç´„ãƒ»ãŠå•åˆã›å…ˆ tel:050-3196-3129</p>
      <p class="hidden-md hidden-lg"><a href="tel:050-3196-3129" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="mailto:bluepaws2018@gmail.com" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "ã‚¹ã‚¿ãƒƒãƒ•ã®ã”ç´¹ä»‹"
    subtitle = "çœ‹æ¿çŠ¬ã¯ã‚ªãƒ¼ã‚¹ãƒˆãƒ©ãƒªã‚¢ãƒ³ãƒ»ãƒ©ãƒ–ãƒ©ãƒ‰ã‚¥ãƒ¼ãƒ‰ãƒ«ã®ãƒ—ãƒ¼&ãƒ©ãƒƒãƒ†å…„å¼Ÿã€‚ãŸã¾ã€œã«å‡ºå‹¤ã—ã¾ã™ğŸ¾<br>(ãƒ¯ãƒ³ã‚³ãŒè‹¦æ‰‹ãªå­ã¯ã€äºˆç´„ã®éš›ã«ãŠä¼ãˆãã ã•ã„ã€‚è‡ªå®…ã§å¾…æ©Ÿã—ã¾ã™ã€‚)"

[params.review]
    enable = true
    title = "ãŠå®¢æ§˜ã®å£°"

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.course]
    enable = true

[params.intro]
    enable = true
    icon = "fa fa-flag-o"
    title = "ãƒ‰ãƒƒã‚°ã‚µãƒ­ãƒ³ ãƒ–ãƒ«ãƒ¼ãƒ‘ã‚¦ã‚º"
    subtitle = "ã‚¤ãƒŒã®ã‚­ãƒ¢ãƒã‚’å¤§åˆ‡ã«ã€ãƒãƒ³ãƒ„ãƒ¼ãƒ¯ãƒ³ã®ä¸å¯§ãªãƒˆãƒªãƒŸãƒ³ã‚°ã§ã‚ˆã‚Šå¯æ„›ãã—ã¾ã™â™ª"
    subtitle2 = "ãƒ—ãƒ©ã‚¤ãƒ™ãƒ¼ãƒˆã‚µãƒ­ãƒ³ã®ãŸã‚ã€å¾…ã¡æ™‚é–“ã‚‚ã‚²ãƒ¼ã‚¸ãƒ•ãƒªãƒ¼ã§ã®ã‚“ã³ã‚Šã€ãƒ¯ãƒ³ã‚³ãŒè‹¦æ‰‹ãªå­ã‚‚å®‰å¿ƒã€‚"
    subtitle3 = "ã‚¤ãƒŒã¨ãƒ’ãƒˆã®ç´ æ•µãªæ¯æ—¥ã®ãŸã‚ã«ã€BLUE PAWSã‚’ã€‚"
    subtitle4 = ""
    subtitle5 = ""
    subtitle6 = ""
    link_url = "#"
    link_text = ""

[params.instafeed]
    enable = true
    link = "{{link}}"
    image = "{{image}}"
    caption = "{{caption}}"

[params.reserve]
    enable = true
    icon = ""
    title = "ã”äºˆç´„ã«éš›ã—ã¦"
    subtitle = "å½“ã‚µãƒ­ãƒ³ã¯äºˆç´„åˆ¶ãƒ—ãƒ©ã‚¤ãƒ™ãƒ¼ãƒˆã‚µãƒ­ãƒ³ã§ã™ã€‚äº‹å‰ã«LINEã€ãŠé›»è©±ã§ã®ã”äºˆç´„ã‚’ãŠé¡˜ã„ã—ã¾ã™ã€‚"
    subtitle2 = "å–¶æ¥­æ™‚é–“ã¯9:00ï½18:00ã€å®šä¼‘æ—¥ã¯æœ¨æ›œã¨æ—¥æ›œã€ç¥ç¥­æ—¥ã§ã™ã€‚"
    subtitle3 = "ã”äºˆç´„ã®å¤‰æ›´ã€ã‚­ãƒ£ãƒ³ã‚»ãƒ«ã¯å‰æ—¥ã¾ã§ã«ãŠé¡˜ã„ã—ã¾ã™ã€‚"
    subtitle4 = "ç›¸äº’æ„ŸæŸ“é˜²æ­¢ã«ã”å”åŠ›ä¸‹ã•ã„ã€‚1å¹´ä»¥å†…ã®æ··åˆãƒ¯ã‚¯ãƒãƒ³æ¥ç¨®ã€ç‹‚çŠ¬ç—…äºˆé˜²æ¥ç¨®ã€ãƒãƒŸã€ãƒ€ãƒ‹ã®é§†é™¤å¯¾ç­–ã‚’ãŠé¡˜ã„è‡´ã—ã¾ã™ã€‚"
    subtitle5 = "æŒç—…ã®ã‚ã‚‹ãƒ¯ãƒ³ã¡ã‚ƒã‚“ã¯äº‹å‰ã«ãŠä¼ãˆä¸‹ã•ã„ï¼ˆé‡åº¦ã®å¿ƒè‡“ç—…ã€ã¦ã‚“ã‹ã‚“ã€ãƒ˜ãƒ«ãƒ‹ã‚¢ã®å ´åˆã¯å‹•ç‰©ç—…é™¢ã§ã®ãƒˆãƒªãƒŸãƒ³ã‚°ã‚’ãŠå‹§ã‚ã—ã¾ã™ï¼‰ã€‚"
    subtitle6 = "å™›ã¿ç™–ã®ã‚ã‚‹ãƒ¯ãƒ³ã¡ã‚ƒã‚“ã¯äº‹å‰ã«ã”ç”³å‘Šä¸‹ã•ã„ã€‚æ¯›ç‰ã€ã‚‚ã¤ã‚ŒãŒä¸€èˆ¬çš„ãªç¯„å›²ã‚’è¶…ãˆã‚‹å ´åˆã¯è¿½åŠ æ–™é‡‘ã‚’é ‚ãå ´åˆã€ãƒãƒªã‚«ãƒ³ã§ãƒˆãƒªãƒŸãƒ³ã‚°ã•ã›ã¦é ‚ãå ´åˆã‚‚ã‚ã‚Šã¾ã™ã®ã§ã”äº†æ‰¿ä¸‹ã•ã„ã€‚ï¼‰"
    subtitle7 = "å™›ã‚€ã€æš´ã‚Œã‚‹ã€å¥åº·çŠ¶æ…‹ã®æ‚ªåŒ–ç­‰ã€ãƒˆãƒªãƒŸãƒ³ã‚°ãŒå‡ºæ¥ãªã„å ´åˆã¯ä¸­æ­¢ã™ã‚‹å ´åˆã‚‚ã‚ã‚Šã¾ã™ã€‚ã”äº†æ‰¿ä¸‹ã•ã„ã€‚"
    subtitle8 = "ãŠæ”¯æ‰•ã„ã«ã¯ã€ã‚¯ãƒ¬ã‚¸ãƒƒãƒˆã‚«ãƒ¼ãƒ‰(VISA/MASTER/JCB)ã‚‚ã”åˆ©ç”¨ã„ãŸã ã‘ã¾ã™ã€‚"
    link_url = "#"
    link_text = ""

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
